Fixed runtime error
Program would not start running but fail with a

    java.lang.IllegalArgumentException: "10" key doesn't exist.

This was caused by double incrementing the index of inventory slots,
(0-8)->(2-10) instead of (0-8)->(1-9) as Index->Key